spring:
  profiles:
    active: local
---
spring.config.activate.on-profile: local
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trello?autoReconnect=true&useSSL=false&serverTimezone=Asia/Seoul
    username: ingduk2
    password: Qwer123$

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect

#debug: true


